name: minecraft_bugsmakers
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
#  google_mobile_ads: ^3.0.0
  dio: ^5.3.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  page_transition: ^2.1.0
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  equatable: ^2.0.5
  share_plus: ^7.1.0
  app_tracking_transparency: ^2.0.4
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  firebase_crashlytics: ^3.3.7
  firebase_remote_config: ^4.2.7
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  intl_utils: ^2.8.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true


flutter:
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt Light.ttf

    - family: BungeeColor
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

